services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: monitor-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: monitor_user
      POSTGRES_PASSWORD: monitor_pass
      POSTGRES_DB: monitor_db
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
